### ISSUE TITLE
F103 goes into error on cranking

### ISSUE THREAD

**Issue by rusefillc** [rusefi/wideband#11]
i have F103 rev 3 master firmware https://github.com/rusefi/wideband (no heater commits) go into blue blinking error on cranking

WBO is hard wired to battery
battery is somewhat alive and hooked to constant charger

fast green blinking on power on, forever 
does not seem to go into slow green blinking https://github.com/rusefi/rusefi/wiki/rusEFI-Wideband-Controller#led-decoding

if I attempt cranking fast green turns into blue LED error state

**Comment by rusefillc** [comment]
@mck1117 FYI

**Comment by mck1117** [comment]
What led error? How many blinks?

**Comment by mck1117** [comment]
Is there rusefi attached? Does it have a log?

**Comment by rusefillc** [comment]
i believe it was three blue
and now it stays fast green forever

https://rusefi.com/online/view.php?log=1045

**Comment by mck1117** [comment]
Fast green means it isn't trying to warm up. Set "force o2 sensor heating" in rusefi and see if it tries

**Comment by rusefillc** [comment]
With "force o2 sensor heating" i got slow green blinking and zero on AFR TS gauge :( With F103 I was expecting self-contained mode of operation wow how us CAN "force o2 sensor heating" even playing a role?!

I have to wire AEM for now to unblock me :(

**Comment by mck1117** [comment]
> zero on AFR TS gauge

log? we still log other internal o2 controller parameters.

> With F103 I was expecting self-contained mode of operation wow how us CAN "force o2 sensor heating" even playing a role?!

F103 will still use rusEFI data if present. If not present, it falls back on internal battery sense.

**Comment by rusefillc** [comment]
three blue again https://rusefi.com/online/view.php?log=1046

**Comment by mck1117** [comment]
I see no wideband data at all in those rusEFI logs :(

**Comment by rusefillc** [comment]
Sounds like we are blocked by https://github.com/rusefi/rusefi/issues/4590 - as is it's just too much effort to troubleshoot ECU/WBO CAN comms. Should be much easier

Unfortunately our typical lack of documentation is hurting my productivity here. https://github.com/rusefi/rusefi/wiki/CAN cannot even spell out ECU out / WBO out packet IDs :(

**Comment by rusefillc** [comment]
@mck1117 here's the info you were looking for! you were asking what is not well with F103

**Comment by rusefillc** [comment]
unable to reproduce
