### ISSUE TITLE
4 wire

### ISSUE THREAD

**Issue by rusefillc** [rusefi/wideband#12]
![image](https://user-images.githubusercontent.com/48498823/201796825-e48d29c3-21e3-442e-882e-670dfc5f5bf6.png)

https://ngksparkplugs.com/wp-content/uploads/2019/04/Oxygen-Sensors.pdf

**Comment by rusefillc** [comment]
https://rusefi.com/forum/viewtopic.php?p=46645#p46645

**Comment by mck1117** [comment]
I got one to work here:

https://rusefi.com/forum/viewtopic.php?p=43610#p43610

**Comment by rusefillc** [comment]
Taken care outside of wideband
